FROM node:12
WORKDIR /usr/src/app

RUN chown -R node: /usr/src && \
    apt-get update && \
    apt-get install -y \
      vim less git && \
    npm install -g \
      lerna \
      create-react-app \
      pm2@3.5.1 \
      @storybook/cli && \
    rm -rf /var/lib/apt/lists/*

USER node
VOLUME ["/usr/src/app"]
EXPOSE 3000

CMD lerna bootstrap --hoist && pm2-dev start ./ecosystem.config.js
