version: '3.7'

services:
  backend:
    build:
      context: ./packages/backend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/backend:/usr/src/app
    environment:
      NODE_ENV: development

    ports:
      - 5000:3000
