version: '3.7'

services:
  lerna:
    build:
      context: .
      dockerfile: Dockerfile.dev

    volumes:
      - ./:/usr/src/app

    environment:
      NODE_ENV: development

    depends_on:
      - database

    ports:
      - 6006:6006
      - 5000:5000
      - 3000:3000

  database:
    image: "postgres:11"
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: arya
      POSTGRES_PASSWORD: stark


volumes:
  db-volume:
