FROM node:12
WORKDIR /usr/src/app

RUN chown -R node: /usr/src && \
    apt update && \
    apt install -y \
      vim less git && \
    rm -rf /var/lib/apt/lists/*

USER node
VOLUME ["/usr/src/app"]
EXPOSE 3000

CMD bash
